source "https://supermarket.getchef.com"

cookbook 'apt'
cookbook 'docker',  github: "bflad/chef-docker"
cookbook "mesos", github: "everpeace/cookbook-mesos"

# stuff for layerx
cookbook 'golang',  github: "NOX73/chef-golang"
cookbook 'etcd', '~> 4.1.0', github: "ilackarms/etcd-chef"
cookbook 'layerx', github: "emc-advanced-dev/chef-layerx"
cookbook 'java', '~> 1.42.0'
